[package]
name = "rxmodb"
version = "0.1.5"
description = "RxMoDb is a Motoko Database using Vector for its main storage and BTree for indexes"
repository = "https://github.com/infu/rxmodb"

[dependencies]
base = "0.11.1"
rxmo = "https://github.com/research-ag/rxmo#a588e45e4ae04cec39c4b0df55454a544788e6af"
stableheapbtreemap = "1.3.0"
vector = "0.2.0"
test = "1.2.0"
